# Grundwortschatz Italienisch fuer Sichtwort (Blitzlesen, 6-10 Jahre)
# (wort, typ) - typ: n=Nomen v=Verb a=Adjektiv o=Sonstiges

FUNCTION = [
    ("il", "o"), ("lo", "o"), ("la", "o"), ("i", "o"), ("gli", "o"), ("le", "o"),
    ("un", "o"), ("uno", "o"), ("una", "o"), ("del", "o"), ("della", "o"),
    ("di", "o"), ("a", "o"), ("da", "o"), ("in", "o"), ("con", "o"), ("su", "o"),
    ("per", "o"), ("tra", "o"), ("fra", "o"), ("nel", "o"), ("sul", "o"),
    ("e", "o"), ("o", "o"), ("ma", "o"), ("se", "o"), ("che", "o"), ("non", "o"),
    ("come", "o"), ("quando", "o"), ("dove", "o"), ("perché", "o"), ("chi", "o"),
    ("cosa", "o"), ("quale", "o"), ("quanto", "o"), ("mentre", "o"), ("però", "o"),
    ("io", "o"), ("tu", "o"), ("lui", "o"), ("lei", "o"), ("noi", "o"), ("voi", "o"),
    ("loro", "o"), ("me", "o"), ("te", "o"), ("mi", "o"), ("ti", "o"), ("si", "o"),
    ("ci", "o"), ("vi", "o"), ("ne", "o"), ("gliene", "o"),
    ("questo", "o"), ("questa", "o"), ("questi", "o"), ("queste", "o"),
    ("quello", "o"), ("quella", "o"), ("quelli", "o"), ("quelle", "o"),
    ("mio", "o"), ("mia", "o"), ("miei", "o"), ("mie", "o"),
    ("tuo", "o"), ("tua", "o"), ("suo", "o"), ("sua", "o"),
    ("nostro", "o"), ("nostra", "o"), ("vostro", "o"), ("vostra", "o"),
    ("molto", "o"), ("poco", "o"), ("tanto", "o"), ("troppo", "o"),
    ("più", "o"), ("meno", "o"), ("anche", "o"), ("ancora", "o"), ("già", "o"),
    ("sempre", "o"), ("mai", "o"), ("spesso", "o"), ("oggi", "o"), ("ieri", "o"),
    ("domani", "o"), ("ora", "o"), ("adesso", "o"), ("poi", "o"), ("prima", "o"),
    ("dopo", "o"), ("qui", "o"), ("qua", "o"), ("lì", "o"), ("là", "o"),
    ("sopra", "o"), ("sotto", "o"), ("dentro", "o"), ("fuori", "o"),
    ("davanti", "o"), ("dietro", "o"), ("accanto", "o"), ("vicino", "o"),
    ("lontano", "o"), ("insieme", "o"), ("così", "o"), ("bene", "o"), ("male", "o"),
    ("sì", "o"), ("no", "o"), ("forse", "o"), ("quasi", "o"), ("subito", "o"),
    ("presto", "o"), ("tardi", "o"), ("piano", "o"), ("tutto", "o"), ("ogni", "o"),
    ("niente", "o"), ("nessuno", "o"), ("qualcosa", "o"), ("qualcuno", "o"),
    ("due", "o"), ("tre", "o"), ("quattro", "o"), ("cinque", "o"), ("sei", "o"),
    ("sette", "o"), ("otto", "o"), ("nove", "o"), ("dieci", "o"), ("undici", "o"),
    ("dodici", "o"), ("venti", "o"), ("cento", "o"), ("mille", "o"),
    ("ciao", "o"), ("grazie", "o"), ("prego", "o"),
]

NOUNS = [
    # Familie & Menschen
    ("mamma", "n"), ("papà", "n"), ("madre", "n"), ("padre", "n"),
    ("figlio", "n"), ("figlia", "n"), ("fratello", "n"), ("sorella", "n"),
    ("nonno", "n"), ("nonna", "n"), ("zio", "n"), ("zia", "n"), ("cugino", "n"),
    ("nipote", "n"), ("bambino", "n"), ("bambina", "n"), ("ragazzo", "n"),
    ("ragazza", "n"), ("uomo", "n"), ("donna", "n"), ("famiglia", "n"),
    ("amico", "n"), ("amica", "n"), ("gente", "n"), ("persona", "n"),
    ("signore", "n"), ("signora", "n"), ("nome", "n"), ("amicizia", "n"),
    # Schule
    ("scuola", "n"), ("maestra", "n"), ("maestro", "n"), ("classe", "n"),
    ("banco", "n"), ("quaderno", "n"), ("libro", "n"), ("penna", "n"),
    ("matita", "n"), ("gomma", "n"), ("astuccio", "n"), ("zaino", "n"),
    ("colla", "n"), ("righello", "n"), ("lavagna", "n"), ("compito", "n"),
    ("lezione", "n"), ("alunno", "n"), ("pagina", "n"), ("parola", "n"),
    ("lettera", "n"), ("numero", "n"), ("disegno", "n"), ("colore", "n"),
    ("foglio", "n"), ("cartella", "n"), ("esercizio", "n"), ("storia", "n"),
    ("favola", "n"), ("racconto", "n"), ("domanda", "n"), ("risposta", "n"),
    # Tiere
    ("cane", "n"), ("gatto", "n"), ("topo", "n"), ("cavallo", "n"), ("mucca", "n"),
    ("pecora", "n"), ("maiale", "n"), ("gallina", "n"), ("gallo", "n"),
    ("pulcino", "n"), ("anatra", "n"), ("uccello", "n"), ("pesce", "n"),
    ("rana", "n"), ("tartaruga", "n"), ("coniglio", "n"), ("lupo", "n"),
    ("orso", "n"), ("volpe", "n"), ("leone", "n"), ("tigre", "n"),
    ("elefante", "n"), ("scimmia", "n"), ("giraffa", "n"), ("serpente", "n"),
    ("ragno", "n"), ("ape", "n"), ("farfalla", "n"), ("formica", "n"),
    ("mosca", "n"), ("lumaca", "n"), ("riccio", "n"), ("cervo", "n"),
    ("delfino", "n"), ("balena", "n"), ("gufo", "n"), ("aquila", "n"),
    ("cigno", "n"), ("asino", "n"), ("capra", "n"), ("pappagallo", "n"),
    ("animale", "n"), ("coda", "n"), ("ala", "n"), ("nido", "n"),
    # Essen
    ("pane", "n"), ("latte", "n"), ("acqua", "n"), ("succo", "n"), ("mela", "n"),
    ("pera", "n"), ("banana", "n"), ("uva", "n"), ("fragola", "n"),
    ("arancia", "n"), ("limone", "n"), ("ciliegia", "n"), ("anguria", "n"),
    ("pomodoro", "n"), ("patata", "n"), ("carota", "n"), ("insalata", "n"),
    ("zucca", "n"), ("cipolla", "n"), ("pasta", "n"), ("pizza", "n"),
    ("riso", "n"), ("minestra", "n"), ("zuppa", "n"), ("carne", "n"),
    ("pollo", "n"), ("uovo", "n"), ("formaggio", "n"), ("burro", "n"),
    ("marmellata", "n"), ("miele", "n"), ("zucchero", "n"), ("sale", "n"),
    ("olio", "n"), ("torta", "n"), ("biscotto", "n"), ("gelato", "n"),
    ("cioccolato", "n"), ("caramella", "n"), ("merenda", "n"), ("colazione", "n"),
    ("pranzo", "n"), ("cena", "n"), ("cibo", "n"), ("caffè", "n"),
    ("piatto", "n"), ("bicchiere", "n"), ("cucchiaio", "n"), ("forchetta", "n"),
    ("coltello", "n"), ("tazza", "n"), ("bottiglia", "n"),
    # Koerper
    ("testa", "n"), ("capelli", "n"), ("occhio", "n"), ("orecchio", "n"),
    ("naso", "n"), ("bocca", "n"), ("dente", "n"), ("lingua", "n"),
    ("collo", "n"), ("spalla", "n"), ("braccio", "n"), ("mano", "n"),
    ("dito", "n"), ("gamba", "n"), ("piede", "n"), ("ginocchio", "n"),
    ("pancia", "n"), ("schiena", "n"), ("cuore", "n"), ("faccia", "n"),
    ("viso", "n"), ("corpo", "n"), ("pelle", "n"), ("osso", "n"),
    # Natur
    ("sole", "n"), ("luna", "n"), ("stella", "n"), ("cielo", "n"), ("nuvola", "n"),
    ("pioggia", "n"), ("neve", "n"), ("vento", "n"), ("temporale", "n"),
    ("arcobaleno", "n"), ("mare", "n"), ("lago", "n"), ("fiume", "n"),
    ("montagna", "n"), ("collina", "n"), ("bosco", "n"), ("albero", "n"),
    ("foglia", "n"), ("fiore", "n"), ("erba", "n"), ("prato", "n"),
    ("campo", "n"), ("sabbia", "n"), ("spiaggia", "n"), ("onda", "n"),
    ("terra", "n"), ("pietra", "n"), ("sasso", "n"), ("isola", "n"),
    ("giardino", "n"), ("orto", "n"), ("frutto", "n"), ("seme", "n"),
    ("radice", "n"), ("ramo", "n"), ("pianta", "n"), ("fuoco", "n"),
    ("ghiaccio", "n"), ("nebbia", "n"), ("stagione", "n"), ("primavera", "n"),
    ("estate", "n"), ("autunno", "n"), ("inverno", "n"), ("aria", "n"),
    # Haus & Dinge
    ("casa", "n"), ("porta", "n"), ("finestra", "n"), ("tetto", "n"), ("muro", "n"),
    ("scala", "n"), ("stanza", "n"), ("camera", "n"), ("cucina", "n"),
    ("bagno", "n"), ("letto", "n"), ("cuscino", "n"), ("coperta", "n"),
    ("tavolo", "n"), ("sedia", "n"), ("divano", "n"), ("armadio", "n"),
    ("specchio", "n"), ("lampada", "n"), ("luce", "n"), ("chiave", "n"),
    ("orologio", "n"), ("telefono", "n"), ("televisione", "n"), ("giornale", "n"),
    ("borsa", "n"), ("scatola", "n"), ("cesto", "n"), ("secchio", "n"),
    ("sapone", "n"), ("asciugamano", "n"), ("pettine", "n"), ("candela", "n"),
    # Verkehr & Ort
    ("macchina", "n"), ("bicicletta", "n"), ("treno", "n"), ("autobus", "n"),
    ("aereo", "n"), ("barca", "n"), ("nave", "n"), ("camion", "n"),
    ("strada", "n"), ("via", "n"), ("piazza", "n"), ("ponte", "n"),
    ("città", "n"), ("paese", "n"), ("negozio", "n"), ("mercato", "n"),
    ("ospedale", "n"), ("chiesa", "n"), ("parco", "n"), ("cinema", "n"),
    ("biblioteca", "n"), ("stazione", "n"), ("fattoria", "n"), ("castello", "n"),
    # Spiel & Kleidung
    ("gioco", "n"), ("giocattolo", "n"), ("palla", "n"), ("pallone", "n"),
    ("bambola", "n"), ("altalena", "n"), ("scivolo", "n"), ("tamburo", "n"),
    ("chitarra", "n"), ("festa", "n"), ("regalo", "n"), ("palloncino", "n"),
    ("vestito", "n"), ("maglia", "n"), ("maglione", "n"), ("camicia", "n"),
    ("pantaloni", "n"), ("gonna", "n"), ("calza", "n"), ("scarpa", "n"),
    ("stivale", "n"), ("cappello", "n"), ("giacca", "n"), ("sciarpa", "n"),
    ("guanto", "n"), ("cappotto", "n"), ("pigiama", "n"), ("bottone", "n"),
    # Zeit
    ("giorno", "n"), ("notte", "n"), ("mattina", "n"), ("sera", "n"),
    ("pomeriggio", "n"), ("minuto", "n"), ("settimana", "n"), ("mese", "n"),
    ("anno", "n"), ("tempo", "n"), ("lunedì", "n"), ("martedì", "n"),
    ("mercoledì", "n"), ("giovedì", "n"), ("venerdì", "n"), ("sabato", "n"),
    ("domenica", "n"), ("compleanno", "n"),
    # Abstrakt
    ("amore", "n"), ("gioia", "n"), ("paura", "n"), ("sogno", "n"), ("idea", "n"),
    ("voce", "n"), ("suono", "n"), ("rumore", "n"), ("canzone", "n"),
    ("musica", "n"), ("ballo", "n"), ("sport", "n"), ("squadra", "n"),
    ("lavoro", "n"), ("vita", "n"), ("mondo", "n"), ("forza", "n"),
    ("sorriso", "n"), ("bacio", "n"), ("aiuto", "n"),
]

VERBS = [
    ("essere", "v"), ("avere", "v"), ("fare", "v"), ("dire", "v"), ("andare", "v"),
    ("venire", "v"), ("stare", "v"), ("dare", "v"), ("vedere", "v"),
    ("sapere", "v"), ("potere", "v"), ("volere", "v"), ("dovere", "v"),
    ("mettere", "v"), ("prendere", "v"), ("parlare", "v"), ("trovare", "v"),
    ("sentire", "v"), ("lasciare", "v"), ("guardare", "v"), ("portare", "v"),
    ("mangiare", "v"), ("bere", "v"), ("dormire", "v"), ("correre", "v"),
    ("camminare", "v"), ("saltare", "v"), ("giocare", "v"), ("leggere", "v"),
    ("scrivere", "v"), ("disegnare", "v"), ("colorare", "v"), ("contare", "v"),
    ("imparare", "v"), ("insegnare", "v"), ("studiare", "v"), ("pensare", "v"),
    ("credere", "v"), ("ricordare", "v"), ("dimenticare", "v"), ("capire", "v"),
    ("ascoltare", "v"), ("cantare", "v"), ("ballare", "v"), ("ridere", "v"),
    ("piangere", "v"), ("gridare", "v"), ("chiamare", "v"), ("rispondere", "v"),
    ("chiedere", "v"), ("aprire", "v"), ("chiudere", "v"), ("entrare", "v"),
    ("uscire", "v"), ("salire", "v"), ("scendere", "v"), ("tornare", "v"),
    ("arrivare", "v"), ("partire", "v"), ("cadere", "v"), ("alzare", "v"),
    ("sedere", "v"), ("aspettare", "v"), ("cercare", "v"), ("perdere", "v"),
    ("vincere", "v"), ("comprare", "v"), ("vendere", "v"), ("pagare", "v"),
    ("aiutare", "v"), ("lavorare", "v"), ("lavare", "v"), ("pulire", "v"),
    ("cucinare", "v"), ("tagliare", "v"), ("rompere", "v"), ("costruire", "v"),
    ("crescere", "v"), ("nascere", "v"), ("vivere", "v"), ("amare", "v"),
    ("baciare", "v"), ("abbracciare", "v"), ("toccare", "v"), ("tenere", "v"),
    ("tirare", "v"), ("spingere", "v"), ("lanciare", "v"), ("nuotare", "v"),
    ("volare", "v"), ("guidare", "v"), ("viaggiare", "v"), ("visitare", "v"),
    ("incontrare", "v"), ("conoscere", "v"), ("regalare", "v"), ("sorridere", "v"),
    ("svegliare", "v"), ("vestire", "v"), ("mostrare", "v"), ("nascondere", "v"),
    ("finire", "v"), ("cominciare", "v"), ("continuare", "v"), ("provare", "v"),
    ("piacere", "v"), ("servire", "v"), ("usare", "v"), ("cambiare", "v"),
    ("girare", "v"), ("passare", "v"), ("restare", "v"), ("diventare", "v"),
    ("sembrare", "v"), ("respirare", "v"), ("soffiare", "v"), ("accendere", "v"),
    ("spegnere", "v"), ("suonare", "v"), ("dipingere", "v"), ("incollare", "v"),
    ("piegare", "v"), ("misurare", "v"), ("pesare", "v"), ("raccogliere", "v"),
    ("seminare", "v"), ("scegliere", "v"),
]

ADJECTIVES = [
    ("grande", "a"), ("piccolo", "a"), ("alto", "a"), ("basso", "a"),
    ("lungo", "a"), ("corto", "a"), ("largo", "a"), ("stretto", "a"),
    ("grosso", "a"), ("magro", "a"), ("forte", "a"), ("debole", "a"),
    ("veloce", "a"), ("lento", "a"), ("nuovo", "a"), ("vecchio", "a"),
    ("giovane", "a"), ("bello", "a"), ("brutto", "a"), ("buono", "a"),
    ("cattivo", "a"), ("bravo", "a"), ("gentile", "a"), ("felice", "a"),
    ("contento", "a"), ("triste", "a"), ("allegro", "a"), ("arrabbiato", "a"),
    ("stanco", "a"), ("malato", "a"), ("sano", "a"), ("caldo", "a"),
    ("freddo", "a"), ("bagnato", "a"), ("asciutto", "a"), ("sporco", "a"),
    ("pulito", "a"), ("pieno", "a"), ("vuoto", "a"), ("aperto", "a"),
    ("chiuso", "a"), ("facile", "a"), ("difficile", "a"), ("giusto", "a"),
    ("sbagliato", "a"), ("vero", "a"), ("falso", "a"), ("dolce", "a"),
    ("salato", "a"), ("amaro", "a"), ("morbido", "a"), ("duro", "a"),
    ("liscio", "a"), ("leggero", "a"), ("pesante", "a"), ("chiaro", "a"),
    ("scuro", "a"), ("luminoso", "a"), ("colorato", "a"), ("bianco", "a"),
    ("nero", "a"), ("rosso", "a"), ("blu", "a"), ("verde", "a"),
    ("giallo", "a"), ("azzurro", "a"), ("arancione", "a"), ("viola", "a"),
    ("rosa", "a"), ("marrone", "a"), ("grigio", "a"), ("dorato", "a"),
    ("primo", "a"), ("ultimo", "a"), ("prossimo", "a"), ("solo", "a"),
    ("altro", "a"), ("stesso", "a"), ("curioso", "a"), ("simpatico", "a"),
    ("divertente", "a"), ("noioso", "a"), ("silenzioso", "a"), ("rumoroso", "a"),
    ("coraggioso", "a"), ("timido", "a"), ("generoso", "a"), ("affamato", "a"),
    ("sicuro", "a"), ("libero", "a"), ("importante", "a"), ("famoso", "a"),
    ("ricco", "a"), ("povero", "a"), ("pericoloso", "a"), ("tranquillo", "a"),
    ("calmo", "a"), ("meraviglioso", "a"), ("magico", "a"), ("strano", "a"),
    ("buffo", "a"), ("fresco", "a"), ("maturo", "a"), ("dispettoso", "a"),
]

POOL = FUNCTION + NOUNS + VERBS + ADJECTIVES

# Aus dem Pool gestrichen, um auf genau 500 zu kommen: seltenere/speziellere
# Woerter, Varianten (fra/tra, qua/qui) und Doppelungen im Bedeutungsfeld.
REMOVE = {
    # Funktionswoerter
    "gliene", "della", "sul", "però", "mentre", "qualcosa", "qualcuno",
    "nessuno", "accanto", "undici", "dodici", "venti", "queste", "quelli",
    "quelle", "miei", "mie", "nostra", "vostra", "prego", "fra", "qua",
    "adesso", "là", "nel", "del", "spesso", "quale", "quanto", "cento",
    "mille", "tanto",
    # Nomen
    "cugino", "nipote", "signore",
    "righello", "astuccio", "colla", "alunno", "esercizio", "cartella",
    "racconto", "compito",
    "gallo", "pulcino", "anatra", "tartaruga", "giraffa", "serpente",
    "lumaca", "riccio", "cervo", "balena", "gufo", "aquila", "cigno",
    "asino", "capra", "pappagallo", "ala", "nido",
    "succo", "ciliegia", "anguria", "zucca", "cipolla", "minestra",
    "marmellata", "miele", "olio", "merenda", "caffè", "insalata",
    "spalla", "ginocchio", "schiena", "viso", "pelle", "osso", "collo",
    "temporale", "collina", "prato", "sabbia", "onda", "pietra", "isola",
    "orto", "seme", "radice", "nebbia", "stagione", "aria", "frutto",
    "muro", "stanza", "cuscino", "coperta", "divano", "armadio", "specchio",
    "lampada", "televisione", "giornale", "cesto", "secchio", "sapone",
    "asciugamano", "pettine", "candela",
    "nave", "camion", "piazza", "mercato", "ospedale", "chiesa", "cinema",
    "biblioteca", "stazione", "fattoria",
    "giocattolo", "pallone", "altalena", "scivolo", "tamburo", "chitarra",
    "palloncino", "maglione", "camicia", "stivale", "sciarpa", "cappotto",
    "pigiama", "bottone",
    "pomeriggio", "minuto",
    "idea", "suono", "rumore", "ballo", "sport", "squadra", "forza",
    "bacio", "sorriso",
    "amicizia", "gente", "favola", "lezione", "banco", "foglio", "pagina",
    "formica", "mosca", "scimmia", "delfino", "volpe", "limone", "riso",
    "burro", "zucchero", "cibo", "bicchiere", "tazza", "lingua", "pancia",
    "corpo", "ghiaccio", "ramo", "campo", "sasso", "paese", "via", "ponte",
    "calza", "guanto", "aiuto",
    # Verben
    "seminare", "misurare", "pesare", "piegare", "incollare", "soffiare",
    "respirare", "sembrare", "diventare", "restare", "continuare", "provare",
    "servire", "vestire", "mostrare", "svegliare", "visitare", "viaggiare",
    "regalare", "lanciare", "spingere", "baciare", "raccogliere", "scegliere",
    "sedere", "nascondere", "dipingere",
    # Adjektive
    "dispettoso", "maturo", "buffo", "magico", "meraviglioso", "calmo",
    "pericoloso", "famoso", "importante", "libero", "generoso", "dorato",
    "luminoso", "prossimo", "stesso", "amaro", "salato", "liscio", "colorato",
}

WORDS = [(w, t) for w, t in POOL if w not in REMOVE]

# Reserve-Woerter, falls auf 500 aufgefuellt werden muss
EXTRA = [
    ("scoiattolo", "n"), ("pinguino", "n"), ("cammello", "n"), ("zebra", "n"),
    ("cavalletta", "n"), ("coccinella", "n"), ("piuma", "n"), ("zampa", "n"),
    ("guscio", "n"), ("stalla", "n"), ("fieno", "n"), ("trattore", "n"),
    ("mulino", "n"), ("pozzo", "n"), ("sentiero", "n"), ("valle", "n"),
    ("grotta", "n"), ("deserto", "n"), ("foresta", "n"), ("cascata", "n"),
    ("tuono", "n"), ("lampo", "n"), ("brina", "n"), ("rugiada", "n"),
    ("farina", "n"), ("pesca", "n"), ("prugna", "n"), ("noce", "n"),
    ("mandorla", "n"), ("spinaci", "n"), ("fagiolo", "n"), ("pisello", "n"),
    ("panino", "n"), ("frittata", "n"), ("budino", "n"), ("succhiello", "n"),
]

if __name__ == "__main__":
    from collections import Counter
    print("total", len(WORDS))
    print(Counter(t for _, t in WORDS))
    dups = [w for w, c in Counter(w for w, _ in WORDS).items() if c > 1]
    print("dups", dups)
