# -*- coding: utf-8 -*-
"""Rohliste Grundwortschatz Rumaenisch (ro500) fuer Sichtwort.
Feld 1 = Wort (ohne Silbentrennung), Feld 2 = n/v/a/o
"""

WORDS = [
    # --- Pronomen / Personen ---
    ("eu", "o"), ("tu", "o"), ("el", "o"), ("ea", "o"), ("noi", "o"),
    ("voi", "o"), ("ei", "o"), ("ele", "o"), ("mine", "o"), ("tine", "o"),
    ("lui", "o"), ("lor", "o"), ("meu", "o"), ("mea", "o"), ("mei", "o"),
    ("mele", "o"), ("tău", "o"), ("ta", "o"), ("tăi", "o"), ("tale", "o"),
    ("său", "o"), ("sa", "o"), ("nostru", "o"), ("noastră", "o"),
    ("noștri", "o"), ("vostru", "o"), ("voastră", "o"),
    ("cine", "o"), ("ce", "o"), ("care", "o"), ("cui", "o"), ("ceva", "o"),
    ("cineva", "o"), ("nimic", "o"), ("nimeni", "o"), ("tot", "o"),
    ("toată", "o"), ("toți", "o"), ("toate", "o"), ("altul", "o"),
    ("alta", "o"), ("fiecare", "o"), ("acesta", "o"), ("aceasta", "o"),
    ("acestea", "o"), ("acela", "o"), ("aceea", "o"), ("asta", "o"),
    ("aici", "o"), ("acolo", "o"),

    # --- Artikel / Determinanten ---
    ("un", "o"), ("o", "o"), ("niște", "o"), ("unii", "o"), ("unele", "o"),
    ("cel", "o"), ("cea", "o"), ("cei", "o"), ("cele", "o"),

    # --- Praepositionen ---
    ("la", "o"), ("în", "o"), ("pe", "o"), ("cu", "o"), ("de", "o"),
    ("din", "o"), ("dintre", "o"), ("pentru", "o"), ("prin", "o"),
    ("spre", "o"), ("sub", "o"), ("peste", "o"), ("lângă", "o"),
    ("între", "o"), ("fără", "o"), ("până", "o"), ("către", "o"),
    ("despre", "o"), ("după", "o"), ("înainte", "o"), ("înapoi", "o"),

    # --- Konjunktionen ---
    ("și", "o"), ("sau", "o"), ("dar", "o"), ("că", "o"), ("ca", "o"),
    ("dacă", "o"), ("deci", "o"), ("însă", "o"), ("ori", "o"), ("nici", "o"),
    ("ci", "o"), ("decât", "o"),

    # --- Adverbien / Partikeln ---
    ("nu", "o"), ("da", "o"), ("unde", "o"), ("când", "o"), ("cum", "o"),
    ("cât", "o"), ("acum", "o"), ("atunci", "o"), ("azi", "o"), ("ieri", "o"),
    ("mâine", "o"), ("mereu", "o"), ("iar", "o"), ("apoi", "o"),
    ("deja", "o"), ("încă", "o"), ("foarte", "o"), ("mai", "o"),
    ("prea", "o"), ("puțin", "o"), ("mult", "o"), ("bine", "o"),
    ("repede", "o"), ("încet", "o"), ("sus", "o"), ("jos", "o"),
    ("afară", "o"), ("înăuntru", "o"), ("aproape", "o"), ("departe", "o"),
    ("împreună", "o"), ("poate", "o"), ("sigur", "o"), ("gata", "o"),
    ("iată", "o"), ("așa", "o"), ("altfel", "o"), ("chiar", "o"),
    ("doar", "o"), ("numai", "o"), ("totuși", "o"), ("niciodată", "o"),
    ("uneori", "o"), ("adesea", "o"), ("imediat", "o"), ("devreme", "o"),
    ("târziu", "o"), ("astăzi", "o"), ("mâinile", "o"),

    # --- Zahlen ---
    ("zero", "o"), ("unu", "o"), ("doi", "o"), ("trei", "o"), ("patru", "o"),
    ("cinci", "o"), ("șase", "o"), ("șapte", "o"), ("opt", "o"),
    ("nouă", "o"), ("zece", "o"), ("unsprezece", "o"), ("doisprezece", "o"),
    ("douăzeci", "o"), ("sută", "o"), ("primul", "o"), ("ultimul", "o"),

    # --- Familie & Menschen ---
    ("mamă", "n"), ("tată", "n"), ("frate", "n"), ("soră", "n"),
    ("bunic", "n"), ("bunică", "n"), ("copil", "n"), ("băiat", "n"),
    ("fată", "n"), ("om", "n"), ("familie", "n"), ("părinte", "n"),
    ("unchi", "n"), ("mătușă", "n"), ("văr", "n"), ("prieten", "n"),
    ("prietenă", "n"), ("bebeluș", "n"), ("doamnă", "n"), ("domn", "n"),
    ("nume", "n"), ("vecin", "n"),

    # --- Schule ---
    ("școală", "n"), ("clasă", "n"), ("elev", "n"), ("elevă", "n"),
    ("învățător", "n"), ("învățătoare", "n"), ("profesor", "n"),
    ("carte", "n"), ("caiet", "n"), ("creion", "n"), ("pix", "n"),
    ("stilou", "n"), ("gumă", "n"), ("penar", "n"), ("ghiozdan", "n"),
    ("bancă", "n"), ("tablă", "n"), ("cretă", "n"), ("hârtie", "n"),
    ("foaie", "n"), ("pagină", "n"), ("literă", "n"), ("cuvânt", "n"),
    ("propoziție", "n"), ("poveste", "n"), ("poezie", "n"), ("desen", "n"),
    ("culoare", "n"), ("temă", "n"), ("lecție", "n"), ("pauză", "n"),
    ("joc", "n"), ("jucărie", "n"), ("minge", "n"), ("păpușă", "n"),
    ("riglă", "n"), ("foarfecă", "n"), ("lipici", "n"), ("calculator", "n"),
    ("ceas", "n"), ("hartă", "n"), ("glob", "n"), ("grădiniță", "n"),
    ("bibliotecă", "n"), ("muzeu", "n"),

    # --- Haus & Dinge ---
    ("casă", "n"), ("ușă", "n"), ("fereastră", "n"), ("cameră", "n"),
    ("bucătărie", "n"), ("baie", "n"), ("pat", "n"), ("masă", "n"),
    ("scaun", "n"), ("dulap", "n"), ("canapea", "n"), ("covor", "n"),
    ("oglindă", "n"), ("lampă", "n"), ("perdea", "n"), ("cheie", "n"),
    ("poartă", "n"), ("gard", "n"), ("curte", "n"), ("grădină", "n"),
    ("acoperiș", "n"), ("perete", "n"), ("podea", "n"), ("scară", "n"),
    ("cuptor", "n"), ("frigider", "n"), ("farfurie", "n"), ("pahar", "n"),
    ("lingură", "n"), ("furculiță", "n"), ("cuțit", "n"), ("oală", "n"),
    ("cană", "n"), ("sticlă", "n"), ("prosop", "n"), ("săpun", "n"),
    ("perie", "n"), ("pieptene", "n"), ("pernă", "n"), ("pătură", "n"),
    ("coș", "n"), ("cutie", "n"), ("saltea", "n"),

    # --- Kleidung ---
    ("haină", "n"), ("rochie", "n"), ("pantalon", "n"), ("cămașă", "n"),
    ("fustă", "n"), ("pantof", "n"), ("ciorap", "n"), ("căciulă", "n"),
    ("mănușă", "n"), ("jachetă", "n"), ("bluză", "n"), ("nasture", "n"),
    ("buzunar", "n"), ("cizmă", "n"), ("fular", "n"),

    # --- Essen ---
    ("pâine", "n"), ("apă", "n"), ("lapte", "n"), ("unt", "n"),
    ("brânză", "n"), ("ou", "n"), ("carne", "n"), ("pește", "n"),
    ("orez", "n"), ("cartof", "n"), ("morcov", "n"), ("roșie", "n"),
    ("castravete", "n"), ("ceapă", "n"), ("usturoi", "n"), ("salată", "n"),
    ("supă", "n"), ("ciorbă", "n"), ("mămăligă", "n"), ("plăcintă", "n"),
    ("prăjitură", "n"), ("tort", "n"), ("ciocolată", "n"), ("bomboană", "n"),
    ("zahăr", "n"), ("sare", "n"), ("miere", "n"), ("dulceață", "n"),
    ("măr", "n"), ("pară", "n"), ("prună", "n"), ("cireașă", "n"),
    ("căpșună", "n"), ("zmeură", "n"), ("strugure", "n"), ("pepene", "n"),
    ("banană", "n"), ("portocală", "n"), ("lămâie", "n"), ("nucă", "n"),
    ("alună", "n"), ("mâncare", "n"), ("cină", "n"), ("prânz", "n"),
    ("ceai", "n"), ("cafea", "n"), ("suc", "n"), ("înghețată", "n"),
    ("biscuit", "n"), ("covrig", "n"), ("cozonac", "n"), ("făină", "n"),

    # --- Tiere ---
    ("animal", "n"), ("câine", "n"), ("pisică", "n"), ("cal", "n"),
    ("vacă", "n"), ("porc", "n"), ("oaie", "n"), ("capră", "n"),
    ("găină", "n"), ("cocoș", "n"), ("rață", "n"), ("gâscă", "n"),
    ("iepure", "n"), ("urs", "n"), ("lup", "n"), ("vulpe", "n"),
    ("cerb", "n"), ("veveriță", "n"), ("arici", "n"), ("șoarece", "n"),
    ("broască", "n"), ("șarpe", "n"), ("pasăre", "n"), ("vrabie", "n"),
    ("rândunică", "n"), ("barză", "n"), ("bufniță", "n"), ("corb", "n"),
    ("porumbel", "n"), ("albină", "n"), ("fluture", "n"), ("furnică", "n"),
    ("muscă", "n"), ("păianjen", "n"), ("gândac", "n"), ("melc", "n"),
    ("pui", "n"), ("cuib", "n"), ("aripă", "n"), ("coadă", "n"),
    ("labă", "n"), ("blană", "n"), ("pană", "n"), ("leu", "n"),
    ("elefant", "n"), ("maimuță", "n"), ("girafă", "n"), ("delfin", "n"),

    # --- Koerper ---
    ("cap", "n"), ("păr", "n"), ("ochi", "n"), ("ureche", "n"), ("nas", "n"),
    ("gură", "n"), ("dinte", "n"), ("limbă", "n"), ("buză", "n"),
    ("obraz", "n"), ("frunte", "n"), ("bărbie", "n"), ("gât", "n"),
    ("umăr", "n"), ("braț", "n"), ("mână", "n"), ("deget", "n"),
    ("unghie", "n"), ("cot", "n"), ("piept", "n"), ("spate", "n"),
    ("burtă", "n"), ("picior", "n"), ("genunchi", "n"), ("talpă", "n"),
    ("inimă", "n"), ("sânge", "n"), ("os", "n"), ("piele", "n"),

    # --- Natur ---
    ("soare", "n"), ("lună", "n"), ("stea", "n"), ("cer", "n"), ("nor", "n"),
    ("ploaie", "n"), ("zăpadă", "n"), ("ninsoare", "n"), ("vânt", "n"),
    ("furtună", "n"), ("fulger", "n"), ("tunet", "n"), ("curcubeu", "n"),
    ("ceață", "n"), ("gheață", "n"), ("foc", "n"), ("fum", "n"), ("aer", "n"),
    ("pământ", "n"), ("piatră", "n"), ("nisip", "n"), ("munte", "n"),
    ("deal", "n"), ("câmp", "n"), ("pădure", "n"), ("copac", "n"),
    ("pom", "n"), ("frunză", "n"), ("floare", "n"), ("iarbă", "n"),
    ("rădăcină", "n"), ("ramură", "n"), ("sămânță", "n"), ("fruct", "n"),
    ("mare", "n"), ("râu", "n"), ("lac", "n"), ("baltă", "n"),
    ("izvor", "n"), ("val", "n"), ("plajă", "n"), ("insulă", "n"),
    ("peșteră", "n"), ("cărare", "n"),

    # --- Ort & Verkehr ---
    ("drum", "n"), ("stradă", "n"), ("pod", "n"), ("oraș", "n"), ("sat", "n"),
    ("parc", "n"), ("piață", "n"), ("magazin", "n"), ("spital", "n"),
    ("biserică", "n"), ("mașină", "n"), ("tren", "n"), ("autobuz", "n"),
    ("avion", "n"), ("vapor", "n"), ("barcă", "n"), ("bicicletă", "n"),
    ("roată", "n"), ("telefon", "n"), ("televizor", "n"), ("bani", "n"),
    ("doctor", "n"), ("pompier", "n"), ("brutar", "n"), ("bucătar", "n"),

    # --- Zeit & Abstraktes ---
    ("zi", "n"), ("noapte", "n"), ("seară", "n"), ("dimineață", "n"),
    ("an", "n"), ("săptămână", "n"), ("oră", "n"), ("minut", "n"),
    ("clipă", "n"), ("vară", "n"), ("iarnă", "n"), ("primăvară", "n"),
    ("toamnă", "n"), ("anotimp", "n"), ("vreme", "n"), ("sărbătoare", "n"),
    ("vacanță", "n"), ("cadou", "n"), ("petrecere", "n"), ("bucurie", "n"),
    ("vis", "n"), ("somn", "n"), ("muzică", "n"), ("cântec", "n"),
    ("dans", "n"), ("film", "n"), ("loc", "n"), ("lucru", "n"), ("fel", "n"),
    ("parte", "n"), ("lume", "n"), ("viață", "n"), ("putere", "n"),
    ("frică", "n"), ("gând", "n"), ("vorbă", "n"), ("răspuns", "n"),
    ("întrebare", "n"), ("adevăr", "n"), ("greșeală", "n"), ("ajutor", "n"),
    ("grijă", "n"), ("drag", "n"),

    # --- Verben ---
    ("fi", "v"), ("avea", "v"), ("face", "v"), ("merge", "v"), ("veni", "v"),
    ("lua", "v"), ("pune", "v"), ("vedea", "v"), ("ști", "v"),
    ("putea", "v"), ("vrea", "v"), ("zice", "v"), ("spune", "v"),
    ("citi", "v"), ("scrie", "v"), ("învăța", "v"), ("juca", "v"),
    ("cânta", "v"), ("dansa", "v"), ("alerga", "v"), ("sări", "v"),
    ("mânca", "v"), ("bea", "v"), ("dormi", "v"), ("visa", "v"),
    ("trezi", "v"), ("spăla", "v"), ("îmbrăca", "v"), ("ajuta", "v"),
    ("lucra", "v"), ("munci", "v"), ("gândi", "v"), ("uita", "v"),
    ("ține", "v"), ("găsi", "v"), ("căuta", "v"), ("pierde", "v"),
    ("aduce", "v"), ("duce", "v"), ("purta", "v"), ("arunca", "v"),
    ("prinde", "v"), ("deschide", "v"), ("închide", "v"), ("intra", "v"),
    ("ieși", "v"), ("urca", "v"), ("coborî", "v"), ("pleca", "v"),
    ("sosi", "v"), ("aștepta", "v"), ("râde", "v"), ("plânge", "v"),
    ("striga", "v"), ("chema", "v"), ("asculta", "v"), ("auzi", "v"),
    ("privi", "v"), ("simți", "v"), ("atinge", "v"), ("gusta", "v"),
    ("mirosi", "v"), ("tăia", "v"), ("rupe", "v"), ("lipi", "v"),
    ("desena", "v"), ("colora", "v"), ("picta", "v"), ("construi", "v"),
    ("repara", "v"), ("curăța", "v"), ("șterge", "v"), ("aduna", "v"),
    ("număra", "v"), ("măsura", "v"), ("împărți", "v"), ("alege", "v"),
    ("schimba", "v"), ("crește", "v"), ("trăi", "v"), ("iubi", "v"),
    ("plăcea", "v"), ("dori", "v"), ("ruga", "v"), ("mulțumi", "v"),
    ("saluta", "v"), ("întreba", "v"), ("răspunde", "v"), ("povesti", "v"),
    ("explica", "v"), ("arăta", "v"), ("ascunde", "v"), ("zbura", "v"),
    ("înota", "v"), ("pescui", "v"), ("culege", "v"), ("planta", "v"),
    ("uda", "v"), ("hrăni", "v"), ("îngriji", "v"), ("mângâia", "v"),
    ("îmbrățișa", "v"), ("săruta", "v"), ("sta", "v"), ("opri", "v"),
    ("porni", "v"), ("mișca", "v"), ("cădea", "v"), ("ridica", "v"),
    ("împinge", "v"), ("trage", "v"), ("umple", "v"), ("goli", "v"),
    ("fierbe", "v"), ("coace", "v"), ("frige", "v"), ("oferi", "v"),
    ("primi", "v"), ("trimite", "v"), ("cumpăra", "v"), ("vinde", "v"),
    ("plăti", "v"), ("călători", "v"), ("vizita", "v"), ("locui", "v"),
    ("începe", "v"), ("termina", "v"), ("încerca", "v"), ("reuși", "v"),
    ("câștiga", "v"), ("lăsa", "v"),

    # --- Adjektive ---
    ("bun", "a"), ("rău", "a"), ("mic", "a"), ("lung", "a"), ("scurt", "a"),
    ("înalt", "a"), ("scund", "a"), ("gros", "a"), ("subțire", "a"),
    ("larg", "a"), ("îngust", "a"), ("greu", "a"), ("ușor", "a"),
    ("tare", "a"), ("moale", "a"), ("cald", "a"), ("rece", "a"),
    ("fierbinte", "a"), ("uscat", "a"), ("ud", "a"), ("umed", "a"),
    ("curat", "a"), ("murdar", "a"), ("nou", "a"), ("vechi", "a"),
    ("tânăr", "a"), ("bătrân", "a"), ("frumos", "a"), ("urât", "a"),
    ("vesel", "a"), ("trist", "a"), ("fericit", "a"), ("supărat", "a"),
    ("liniștit", "a"), ("gălăgios", "a"), ("harnic", "a"), ("leneș", "a"),
    ("cuminte", "a"), ("obraznic", "a"), ("deștept", "a"), ("atent", "a"),
    ("curajos", "a"), ("fricos", "a"), ("puternic", "a"), ("slab", "a"),
    ("sănătos", "a"), ("bolnav", "a"), ("plin", "a"), ("gol", "a"),
    ("luminos", "a"), ("întunecat", "a"), ("alb", "a"), ("negru", "a"),
    ("roșu", "a"), ("galben", "a"), ("verde", "a"), ("albastru", "a"),
    ("maro", "a"), ("gri", "a"), ("roz", "a"), ("mov", "a"),
    ("portocaliu", "a"), ("dulce", "a"), ("acru", "a"), ("amar", "a"),
    ("sărat", "a"), ("gustos", "a"), ("rotund", "a"), ("pătrat", "a"),
    ("drept", "a"), ("strâmb", "a"), ("adânc", "a"), ("bogat", "a"),
    ("sărac", "a"), ("iute", "a"), ("singur", "a"), ("important", "a"),
    ("adevărat", "a"), ("simplu", "a"), ("liber", "a"), ("ocupat", "a"),
    ("dulceag", "a"), ("blând", "a"), ("dor", "n"),
]
